---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshoponweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshoponweb
  template:
    metadata:
      labels:
        app: eshoponweb
    spec:
      containers:
        - name: eshoponweba
          image: maheshr8050/eshoponwebdemo:1
          ports:
            - containerPort: 8085
          env:
            - name: PORT
              value: "8085"
---
apiVersion: v1
kind: Service
metadata:
  name: eshoponweb
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: eshoponweb
